# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8f85852d6636a8181d4e26ebd3d51b7"
name = "CartFlow"
application_url = "https://shopifyapp.cartflow.tech"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cartflow-staging.myshopify.com"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create","orders/paid","orders/updated", "orders/cancelled", "orders/fulfilled"]
  uri = "https://admin.cartflow.tech/api/webhook-integracao/shopify"

[access_scopes]
scopes = "read_orders,read_fulfillments,write_fulfillments,read_products,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = [ "https://shopifyapp.cartflow.tech/api/auth" ]
